config/routes.rb
CountryApp::Application.routes.draw do

  resources :countries
  root :to => "countries#index"

  match 'world' => 'world#index', :as => 'world', :via => :get
  match 'by_population' => 'world#by_population', :as => 'by_population', :via => :get
  match 'by_age' => 'world#by_age', :as => 'by_age', :via => :get
  match 'by_required_service' => 'world#by_required_service', :as => 'by_required_service', :via => :get
  match 'search' => 'world#search', :as => 'search', :via => :get
  match 'results' => 'world#search_results', :as => 'results', :via => :post
  

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :life_expectancy, :mandatory_military_service, :median_age, :name, :population, :gdp
  ALLOWED_COUNTRIES = ["Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola",
        "Anguilla", "Antarctica", "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria",
        "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
        "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil",
        "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia",
        "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China",
        "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo",
        "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba",
        "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)",
        "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia",
        "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar",
        "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea",
        "Guinea-Bissau", "Guyana", "Haiti", "Heard and McDonald Islands", "Holy See (Vatican City State)",
        "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic of", "Iraq",
        "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya",
        "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan",
        "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Macedonia, The Former Yugoslav Republic Of",
        "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique",
        "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of",
        "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
        "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger",
        "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau",
        "Palestinian Territory, Occupied", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation",
        "Rwanda", "Saint Barthelemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia",
        "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
        "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
        "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "Sudan", "Suriname",
        "Svalbard and Jan Mayen", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic",
        "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Timor-Leste",
        "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
        "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
        "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
        "Viet Nam", "Virgin Islands, British", "Virgin Islands, U.S.", "Wallis and Futuna", "Western Sahara",
        "Yemen", "Zambia", "Zimbabwe"]


  validates :name, :presence => true
  validates :population, :presence => true
  validates :life_expectancy, :presence => true
  validates :gdp, :presence => true
  validates :population, :numericality => { :only_integer => true }
  validates :median_age, :numericality => true
  validates :life_expectancy, :numericality => true
  validates_inclusion_of :name, :in => ALLOWED_COUNTRIES

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @countries }
    end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @country = Country.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/new
  # GET /countries/new.json
  def new
    @country = Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = Country.find(params[:id])
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.json
  def update
    @country = Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/world_controller.rb
class WorldController < ApplicationController
  def index
  	@country = Country.order('name')
  end

  def by_population
  	@country = Country.reorder('population DESC')
  end

  def by_age
  	@country = Country.where('median_age > 30').order('median_age')
  end

  def by_required_service
  	@country = Country.where(:mandatory_military_service => true)
  end

  def search 
  	#loads up search.html.haml
  	@search_options = ["All Countries", "Countries with mandatory military service", "Countries without mandatory military service"]
  end

  def search_results
  	@keyword = params[:keyword]
  	session[:recent_search] = @keyword
    @selected_search_option = params[:mandatory_military_service]
    case @selected_search_option
    when "All Countries"
    	@country = Country.where("name LIKE ?", "%#{@keyword}%")
    when "Countries with mandatory military sevice"
    	@country = Country.where(:mandatory_military_service => true).where("name LIKE ?", "%#{@keyword}")
    when 
    	@country = Country.where(:mandatory_military_service => false).where("name LIKE ?", "%#{@keyword}")   
    end 

    if @country.empty?
    	flash[:error] = "Country doesn't exist"
    	redirect_to search_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/world_helper.rb
module WorldHelper
end

app/views/countries/_country.html.haml
%section.country
  %header
    %h1= country.name
  %section.body
    %p
      %b Population:
      = country.population
    %p
      %b Median age:
      = country.median_age
    %p
      %b Life expectancy:
      = country.life_expectancy
    %p
      %b GDP:
      = number_to_currency country.gdp
    %p
      %b Mandatory military service:
      = country.mandatory_military_service

app/views/countries/_form.html.haml
= form_for(@country) do |f|
  - if @country.errors.any?
    #error_explanation
      %h2
        = pluralize(@country.errors.count, "error")
        prohibited this country from being saved:
      %ul
        - @country.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.select :name, Country::ALLOWED_COUNTRIES
  .field
    = f.label :population
    %br/
    = f.number_field :population
  .field
    = f.label :median_age
    %br/
    = f.text_field :median_age
  .field
    = f.label :life_expectancy
    %br/
    = f.text_field :life_expectancy
  .field
    = f.label :gdp
    %br/
    = f.text_field :gdp
  .field
    = f.label :mandatory_military_service
    %br/
    = f.check_box :mandatory_military_service
  .actions
    = f.submit

app/views/countries/edit.html.haml
%h1 Editing country
= render 'form'
= link_to 'Show', @country
|
\#{link_to 'Back', countries_path}

app/views/countries/index.html.haml
%h1 Listing countries
%table
  %tr
    %th Name
    %th Population
    %th Median age
    %th Life expectancy
    %th GDP
    %th Mandatory military service
    %th
    %th
    %th
  - @countries.each do |country|
    %tr
      %td= country.name
      %td= country.population
      %td= country.median_age
      %td= country.life_expectancy
      %td= number_to_currency country.gdp
      %td= country.mandatory_military_service
      %td= link_to 'Show', country
      %td= link_to 'Edit', edit_country_path(country)
      %td= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Country', new_country_path

app/views/countries/new.html.haml
%h1 New country
= render 'form'
= link_to 'Back', countries_path

app/views/countries/show.html.haml
%p#notice= notice
= render @country
= link_to 'Edit', edit_country_path(@country)
|
\#{link_to 'Back', countries_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CountryApp
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = link_to 'World', world_path
    = link_to 'By Age', by_age_path
    = link_to 'By Population', by_population_path
    = link_to 'Countries with required military service', by_required_service_path
    = link_to 'Search', search_path
    - if flash[:error]
      .error_msg
        = flash[:error]
    - if flash[:notice]
      .notice_msg
        = flash[:notice]
    = yield

app/views/world/by_age.html.haml
= render @country

app/views/world/by_population.html.haml
= render @country

app/views/world/by_required_service.html.haml
= render @country

app/views/world/index.html.haml
= render @country

app/views/world/search.html.haml
%h1 Search Customers
- if (session[:recent_search])
  you searched for
  = session[:recent_search]
- else
  %h2 this is your first time searching

= form_tag results_path do
  = label_tag "Search"
  = text_field_tag :keyword
  = select_tag :mandatory_military_service, options_for_select(@search_options)
  = submit_tag "Search"

app/views/world/search_result.html.haml
%h1 Search Result for
= @keyword

= render @country

app/views/world/search_results.html.haml
%h1 Search Result for
= @keyword

= render @country